### ISSUE TITLE
Nut and Collet .STEP/.f3d file

### ISSUE THREAD

**Issue by DRA6N** [makersmakingchange/Oak-Compact-Joystick#6]
Please include the CAD files (f3d) for the nut and collet to use for customizing as per request of the requestee.

**Comment by jakemcivor** [comment]
Thanks for noticing the missing files. I've added them to the repository. Please let us know if you run into any more issues.

Topper_Interface (Portion to create custom topper): 
https://github.com/makersmakingchange/Oak-Compact-Joystick/raw/refs/heads/main/Design_Files/CAD_Files/Topper_Interface/Oak_Topper_Interface.f3d

Topper_Nut: 
https://github.com/makersmakingchange/Oak-Compact-Joystick/raw/refs/heads/main/Design_Files/CAD_Files/Topper_Interface/Oak_Topper_Nut.f3d

Topper_Collet: 
https://github.com/makersmakingchange/Oak-Compact-Joystick/raw/refs/heads/main/Design_Files/CAD_Files/Topper_Interface/Oak_Topper_Collet.f3d
